// <auto-generated />
namespace MovieDbAppByM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MovieDB_v10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MovieDB_v10));
        
        string IMigrationMetadata.Id
        {
            get { return "201810041002219_MovieDB_v1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
